services:
  backend:
    build: ./backend
    container_name: portfolio-backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: portfolio-frontend
    ports:
      - "80:80"
    depends_on:
      - backend